In [1]:
import pandas as pd
# Load the file to inspect its structure
posts = pd.read_csv("posts_table.csv")
posts.head()

,post_id,user_id,full_text,created_at,lang,repost_count,like_count,source
0,1907578844636393679,1810361594586738692,"This is nasty \n\nNASDAQ futures down -4.4%, S...",Wed Apr 02 23:40:12 +0000 2025,en,0,0,Twitter Web App
1,1907578044492968060,2736639061,Investors Panic as U.S. Stock Market Plummets ...,Wed Apr 02 23:37:01 +0000 2025,en,1,0,Twitter Web App
2,1907575218501198232,1850383929829945344,For all the people who have absolutely no conc...,Wed Apr 02 23:25:47 +0000 2025,en,0,2,Twitter for Android
3,1907574739964510255,449290925,As someone who is feeling JVL levels of schade...,Wed Apr 02 23:23:53 +0000 2025,en,0,0,Twitter for Android
4,1907570533836701721,23709151,The fuzziest math is #TrumpTariff Math.,Wed Apr 02 23:07:10 +0000 2025,en,0,0,Twitter for Android

In [2]:
import re

def clean_text_preprocessing1(text):
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)     # Remove URLs
    text = re.sub(r"@\w+", "", text)                        # Remove mentions
    text = re.sub(r"#", "", text)                           # Remove only '#' 
    text = re.sub(r"[^\x00-\x7F]+", "", text)               # Remove emojis (non-ASCII characters)
    text = re.sub(r"\d+", "", text)                         # Remove numerical characters
    return text

# Apply this to DataFrame 
posts['text_preprocessing1'] = posts['full_text'].apply(clean_text_preprocessing1)
posts['text_preprocessing1'].head()

0    This is nasty \n\nNASDAQ futures down -.%, S&a...
1    Investors Panic as U.S. Stock Market Plummets ...
2    For all the people who have absolutely no conc...
3    As someone who is feeling JVL levels of schade...
4               The fuzziest math is TrumpTariff Math.
Name: text_preprocessing1, dtype: object

In [3]:
import string

def clean_text_preprocessing2(text):
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)  # Remove punctuation
    return text

# Apply this to the result of step 1
posts['text_preprocessing_no_punctuation'] = posts['text_preprocessing1'].apply(clean_text_preprocessing2)
posts['text_preprocessing_no_punctuation'].head()

0    This is nasty \n\nNASDAQ futures down  SampP f...
1    Investors Panic as US Stock Market Plummets Ov...
2    For all the people who have absolutely no conc...
3    As someone who is feeling JVL levels of schade...
4                The fuzziest math is TrumpTariff Math
Name: text_preprocessing_no_punctuation, dtype: object

In [4]:
# Convert texts to lowercase
posts['text_preprocessing_no_punctuation'] = \
posts['text_preprocessing_no_punctuation'].map(lambda x: x.lower())
posts['text_preprocessing_no_punctuation'].head()

0    this is nasty \n\nnasdaq futures down  sampp f...
1    investors panic as us stock market plummets ov...
2    for all the people who have absolutely no conc...
3    as someone who is feeling jvl levels of schade...
4                the fuzziest math is trumptariff math
Name: text_preprocessing_no_punctuation, dtype: object

In [5]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    words = text.split()
    filtered = [word for word in words if word not in ENGLISH_STOP_WORDS]
    return " ".join(filtered)

# Apply to cleaned column
posts['text_no_stopwords'] = posts['text_preprocessing_no_punctuation'].apply(remove_stopwords)
posts['text_no_stopwords'].head()

0    nasty nasdaq futures sampp futures tariff news...
1    investors panic stock market plummets trumps t...
2    people absolutely concept tariff amp differs g...
3    feeling jvl levels schadenfreude let just say ...
4                       fuzziest math trumptariff math
Name: text_no_stopwords, dtype: object

In [6]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import pos_tag

# Download required resources
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN
        
def lemmatize_with_pos(text):
    tokens = nltk.word_tokenize(text)
    tagged_tokens = pos_tag(tokens)
    lemmatized = [
        lemmatizer.lemmatize(word, get_wordnet_pos(pos)) 
        for word, pos in tagged_tokens
    ]
    return " ".join(lemmatized)
    
posts['text_lemmatized'] = posts['text_no_stopwords'].apply(lemmatize_with_pos)
posts['text_lemmatized'].head()

[nltk_data] Downloading package punkt to /Users/patnbe/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/patnbe/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/patnbe/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/patnbe/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

0    nasty nasdaq future sampp future tariff news h...
1    investor panic stock market plummet trump tari...
2    people absolutely concept tariff amp differs g...
3    feel jvl level schadenfreude let just say happ...
4                          fuzzy math trumptariff math
Name: text_lemmatized, dtype: object

In [7]:
posts.head()

,post_id,user_id,full_text,created_at,lang,repost_count,like_count,source,text_preprocessing1,text_preprocessing_no_punctuation,text_no_stopwords,text_lemmatized
0,1907578844636393679,1810361594586738692,"This is nasty \n\nNASDAQ futures down -4.4%, S...",Wed Apr 02 23:40:12 +0000 2025,en,0,0,Twitter Web App,"This is nasty \n\nNASDAQ futures down -.%, S&a...",this is nasty \n\nnasdaq futures down sampp f...,nasty nasdaq futures sampp futures tariff news...,nasty nasdaq future sampp future tariff news h...
1,1907578044492968060,2736639061,Investors Panic as U.S. Stock Market Plummets ...,Wed Apr 02 23:37:01 +0000 2025,en,1,0,Twitter Web App,Investors Panic as U.S. Stock Market Plummets ...,investors panic as us stock market plummets ov...,investors panic stock market plummets trumps t...,investor panic stock market plummet trump tari...
2,1907575218501198232,1850383929829945344,For all the people who have absolutely no conc...,Wed Apr 02 23:25:47 +0000 2025,en,0,2,Twitter for Android,For all the people who have absolutely no conc...,for all the people who have absolutely no conc...,people absolutely concept tariff amp differs g...,people absolutely concept tariff amp differs g...
3,1907574739964510255,449290925,As someone who is feeling JVL levels of schade...,Wed Apr 02 23:23:53 +0000 2025,en,0,0,Twitter for Android,As someone who is feeling JVL levels of schade...,as someone who is feeling jvl levels of schade...,feeling jvl levels schadenfreude let just say ...,feel jvl level schadenfreude let just say happ...
4,1907570533836701721,23709151,The fuzziest math is #TrumpTariff Math.,Wed Apr 02 23:07:10 +0000 2025,en,0,0,Twitter for Android,The fuzziest math is TrumpTariff Math.,the fuzziest math is trumptariff math,fuzziest math trumptariff math,fuzzy math trumptariff math

In [8]:
# Export cleaned_text.csv file for using in BERTopic model that is performed in another environment due to the conflict in versions of some libraries used in both models
posts.to_csv('cleaned_text.csv', index=False)

In [9]:
# Tokenize text
tokenized_text = posts['text_lemmatized'].apply(lambda x: x.split())

In [10]:
from gensim import corpora

# Create Dictionary
id2word = corpora.Dictionary(tokenized_text)

# Create Corpus: Term Document Frequency
corpus = [id2word.doc2bow(text) for text in tokenized_text]

In [33]:
from gensim.models.ldamodel import LdaModel

# Train LDA model
lda_model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    num_topics=5, # number of topics
    random_state=100,
    update_every=1,
    chunksize=100,
    passes=10,
    alpha='auto',
    per_word_topics=True
)

In [26]:
# Display topics (word distribution in each topic)
topics = lda_model.print_topics()
for idx, topic in topics:
    print(f"Topic {idx + 1}: {topic}")

Topic 1: 0.059*"rate" + 0.032*"july" + 0.017*"state" + 0.017*"quota" + 0.016*"carney" + 0.016*"set" + 0.014*"help" + 0.013*"growth" + 0.012*"send" + 0.012*"sign"
Topic 2: 0.053*"like" + 0.025*"big" + 0.022*"right" + 0.018*"tell" + 0.017*"look" + 0.016*"job" + 0.016*"b" + 0.016*"uncertainty" + 0.012*"wrong" + 0.011*"lot"
Topic 3: 0.118*"tariff" + 0.068*"trump" + 0.016*"trade" + 0.012*"deal" + 0.011*"say" + 0.011*"war" + 0.010*"just" + 0.010*"country" + 0.009*"do" + 0.009*"amp"
Topic 4: 0.049*"market" + 0.019*"stock" + 0.018*"month" + 0.018*"he" + 0.016*"dollar" + 0.015*"im" + 0.013*"negotiation" + 0.012*"trillion" + 0.012*"lose" + 0.012*"pause"
Topic 5: 0.043*"canada" + 0.040*"tax" + 0.037*"pay" + 0.035*"china" + 0.024*"price" + 0.023*"good" + 0.020*"american" + 0.016*"import" + 0.015*"cost" + 0.014*"business"

In [27]:
# Display topic distribution in each document
lda_model.get_document_topics(corpus)
for i, doc in enumerate(corpus):
    topics = lda_model.get_document_topics(doc)
    print(f"Document {i + 1} Topics: {topics}")

Document 1 Topics: [(0, 0.041822787), (1, 0.062399764), (2, 0.63143444), (3, 0.1503861), (4, 0.113956906)]
Document 2 Topics: [(0, 0.05575785), (1, 0.055793434), (2, 0.613032), (3, 0.15524337), (4, 0.12017332)]
Document 3 Topics: [(0, 0.078425996), (1, 0.052410904), (2, 0.6810659), (3, 0.06494906), (4, 0.1231481)]
Document 4 Topics: [(0, 0.06000134), (1, 0.11877154), (2, 0.60949284), (3, 0.07325762), (4, 0.13847664)]
Document 5 Topics: [(0, 0.06841443), (1, 0.1332278), (2, 0.5562519), (3, 0.083699994), (4, 0.15840589)]
Document 6 Topics: [(0, 0.060377546), (1, 0.19846772), (2, 0.45377937), (3, 0.105858065), (4, 0.18151733)]
Document 7 Topics: [(0, 0.13080464), (1, 0.15697755), (2, 0.5202476), (3, 0.0663411), (4, 0.12562916)]
Document 8 Topics: [(0, 0.057198107), (1, 0.056497354), (2, 0.5201683), (3, 0.23344383), (4, 0.13269235)]
Document 9 Topics: [(0, 0.053785924), (1, 0.051253874), (2, 0.6856232), (3, 0.06378889), (4, 0.1455481)]
Document 10 Topics: [(0, 0.08928684), (1, 0.13518843), (2, 0.5896842), (3, 0.09153985), (4, 0.09430064)]
Document 11 Topics: [(0, 0.050549027), (1, 0.049929798), (2, 0.72036934), (3, 0.06187886), (4, 0.11727297)]
Document 12 Topics: [(0, 0.16604203), (1, 0.04719342), (2, 0.5737402), (3, 0.10438505), (4, 0.10863935)]
Document 13 Topics: [(0, 0.046142038), (1, 0.04557186), (2, 0.7446799), (3, 0.05649209), (4, 0.10711414)]
Document 14 Topics: [(0, 0.06168077), (1, 0.09020624), (2, 0.51062226), (3, 0.075682625), (4, 0.26180804)]
Document 15 Topics: [(0, 0.04205969), (1, 0.041583378), (2, 0.6694303), (3, 0.051398452), (4, 0.19552816)]
Document 16 Topics: [(0, 0.063546985), (1, 0.0626876), (2, 0.61682993), (3, 0.07797239), (4, 0.17896311)]
Document 17 Topics: [(0, 0.04196644), (1, 0.041398916), (2, 0.46728006), (3, 0.051493004), (4, 0.3978616)]
Document 18 Topics: [(0, 0.04769529), (1, 0.04704957), (2, 0.5083277), (3, 0.058519773), (4, 0.33840767)]
Document 19 Topics: [(0, 0.054833136), (1, 0.05416385), (2, 0.62592256), (3, 0.1407081), (4, 0.12437233)]
Document 20 Topics: [(0, 0.04770426), (1, 0.06959905), (2, 0.5310065), (3, 0.05853114), (4, 0.29315904)]
Document 21 Topics: [(0, 0.06441175), (1, 0.06364012), (2, 0.6440126), (3, 0.07880312), (4, 0.14913242)]
Document 22 Topics: [(0, 0.04994923), (1, 0.049273714), (2, 0.6750365), (3, 0.061287835), (4, 0.1644528)]
Document 23 Topics: [(0, 0.17149033), (1, 0.052219115), (2, 0.5874705), (3, 0.06507931), (4, 0.12374076)]
Document 24 Topics: [(0, 0.05189537), (1, 0.05844241), (2, 0.69859666), (3, 0.064060815), (4, 0.1270047)]
Document 25 Topics: [(0, 0.111983284), (1, 0.04534524), (2, 0.59649086), (3, 0.05586782), (4, 0.19031282)]
Document 26 Topics: [(0, 0.05306845), (1, 0.052418455), (2, 0.6814193), (3, 0.06495503), (4, 0.14813872)]
Document 27 Topics: [(0, 0.06192567), (1, 0.12172232), (2, 0.57115144), (3, 0.075350605), (4, 0.16984993)]
Document 28 Topics: [(0, 0.13945764), (1, 0.05458029), (2, 0.5864675), (3, 0.067157686), (4, 0.15233687)]
Document 29 Topics: [(0, 0.051913958), (1, 0.051465657), (2, 0.66321146), (3, 0.09200705), (4, 0.14140183)]
Document 30 Topics: [(0, 0.0559014), (1, 0.055220634), (2, 0.63868535), (3, 0.06841444), (4, 0.18177825)]
Document 31 Topics: [(0, 0.057266444), (1, 0.11133324), (2, 0.52053356), (3, 0.07008804), (4, 0.24077874)]
Document 32 Topics: [(0, 0.036062434), (1, 0.035638884), (2, 0.39370152), (3, 0.044102002), (4, 0.49049518)]
Document 33 Topics: [(0, 0.06568632), (1, 0.065121785), (2, 0.6326049), (3, 0.08120242), (4, 0.15538463)]
Document 34 Topics: [(0, 0.043025468), (1, 0.04252191), (2, 0.66042066), (3, 0.11389058), (4, 0.14014144)]
Document 35 Topics: [(0, 0.04816337), (1, 0.047567483), (2, 0.59690577), (3, 0.05896879), (4, 0.24839456)]
Document 36 Topics: [(0, 0.047422145), (1, 0.047025077), (2, 0.7385419), (3, 0.05789467), (4, 0.10911625)]
Document 37 Topics: [(0, 0.048161667), (1, 0.047565322), (2, 0.59679145), (3, 0.08189451), (4, 0.22558708)]
Document 38 Topics: [(0, 0.048213713), (1, 0.04999981), (2, 0.7307258), (3, 0.059611414), (4, 0.11144929)]
Document 39 Topics: [(0, 0.06989108), (1, 0.06894597), (2, 0.61181915), (3, 0.0857566), (4, 0.16358721)]
Document 40 Topics: [(0, 0.11217978), (1, 0.056354813), (2, 0.6140808), (3, 0.068140134), (4, 0.14924446)]
Document 41 Topics: [(0, 0.06416436), (1, 0.0931355), (2, 0.61915356), (3, 0.07815654), (4, 0.14539006)]
Document 42 Topics: [(0, 0.06705447), (1, 0.06701363), (2, 0.55949503), (3, 0.1541273), (4, 0.15230957)]
Document 43 Topics: [(0, 0.05502655), (1, 0.27382922), (2, 0.43456012), (3, 0.06631104), (4, 0.1702731)]
Document 44 Topics: [(0, 0.06429888), (1, 0.09592791), (2, 0.5632534), (3, 0.07749326), (4, 0.19902653)]
Document 45 Topics: [(0, 0.060459904), (1, 0.05913285), (2, 0.67452973), (3, 0.071075276), (4, 0.1348023)]
Document 46 Topics: [(0, 0.06553285), (1, 0.15817516), (2, 0.54249793), (3, 0.08040897), (4, 0.15338512)]
Document 47 Topics: [(0, 0.07735601), (1, 0.051737763), (2, 0.65883344), (3, 0.06435211), (4, 0.14772062)]
Document 48 Topics: [(0, 0.03468112), (1, 0.034241587), (2, 0.59462893), (3, 0.042486176), (4, 0.29396218)]
Document 49 Topics: [(0, 0.048385527), (1, 0.09872175), (2, 0.5927996), (3, 0.06259681), (4, 0.19749634)]
Document 50 Topics: [(0, 0.045158032), (1, 0.04459443), (2, 0.7286197), (3, 0.07678969), (4, 0.10483814)]
Document 51 Topics: [(0, 0.20152755), (1, 0.039713852), (2, 0.6154193), (3, 0.050026502), (4, 0.0933128)]
Document 52 Topics: [(0, 0.05956949), (1, 0.03981186), (2, 0.50696045), (3, 0.049518663), (4, 0.34413955)]
Document 53 Topics: [(0, 0.15027381), (1, 0.058425963), (2, 0.5824296), (3, 0.07213278), (4, 0.13673788)]
Document 54 Topics: [(0, 0.066987365), (1, 0.06601891), (2, 0.6267242), (3, 0.08818763), (4, 0.15208189)]
Document 55 Topics: [(0, 0.047993004), (1, 0.27685234), (2, 0.4818996), (3, 0.08170496), (4, 0.11155006)]
Document 56 Topics: [(0, 0.056740977), (1, 0.109631516), (2, 0.6312558), (3, 0.06960774), (4, 0.13276394)]
Document 57 Topics: [(0, 0.04181311), (1, 0.18326825), (2, 0.58484024), (3, 0.06463591), (4, 0.12544252)]
Document 58 Topics: [(0, 0.044152852), (1, 0.10712299), (2, 0.44012505), (3, 0.30656645), (4, 0.10203266)]
Document 59 Topics: [(0, 0.15885738), (1, 0.043903317), (2, 0.5986156), (3, 0.05506082), (4, 0.14356291)]
Document 60 Topics: [(0, 0.053976785), (1, 0.07957447), (2, 0.5952034), (3, 0.14800255), (4, 0.12324281)]
Document 61 Topics: [(0, 0.058792986), (1, 0.27060884), (2, 0.4689127), (3, 0.08798684), (4, 0.113698654)]
Document 62 Topics: [(0, 0.07927172), (1, 0.053210836), (2, 0.6379376), (3, 0.064032584), (4, 0.16554724)]
Document 63 Topics: [(0, 0.08936214), (1, 0.059884828), (2, 0.6205302), (3, 0.07207226), (4, 0.15815058)]
Document 64 Topics: [(0, 0.12651128), (1, 0.05809948), (2, 0.5770644), (3, 0.10021061), (4, 0.13811424)]
Document 65 Topics: [(0, 0.05697628), (1, 0.23161277), (2, 0.46958777), (3, 0.1216351), (4, 0.12018804)]
Document 66 Topics: [(0, 0.049706973), (1, 0.048577484), (2, 0.6816205), (3, 0.061477415), (4, 0.1586176)]
Document 67 Topics: [(0, 0.045093875), (1, 0.04549362), (2, 0.7507061), (3, 0.054971993), (4, 0.103734404)]
Document 68 Topics: [(0, 0.09441893), (1, 0.13969263), (2, 0.49969003), (3, 0.07065292), (4, 0.19554546)]
Document 69 Topics: [(0, 0.081555575), (1, 0.0743214), (2, 0.520841), (3, 0.20859087), (4, 0.11469117)]
Document 70 Topics: [(0, 0.15473062), (1, 0.04445778), (2, 0.61494124), (3, 0.056522314), (4, 0.12934807)]
Document 71 Topics: [(0, 0.04893607), (1, 0.07193132), (2, 0.59202033), (3, 0.08296791), (4, 0.2041444)]
Document 72 Topics: [(0, 0.07086977), (1, 0.07004536), (2, 0.60845417), (3, 0.08668805), (4, 0.16394262)]
Document 73 Topics: [(0, 0.049470104), (1, 0.04871731), (2, 0.667342), (3, 0.0601153), (4, 0.17435531)]
Document 74 Topics: [(0, 0.0456345), (1, 0.045018155), (2, 0.4645538), (3, 0.055991173), (4, 0.38880235)]
Document 75 Topics: [(0, 0.045668345), (1, 0.04663429), (2, 0.6876503), (3, 0.058898315), (4, 0.16114873)]
Document 76 Topics: [(0, 0.07461729), (1, 0.075420626), (2, 0.5913709), (3, 0.063225366), (4, 0.1953659)]
Document 77 Topics: [(0, 0.058434762), (1, 0.054741047), (2, 0.68904257), (3, 0.06767838), (4, 0.1301033)]
Document 78 Topics: [(0, 0.057529487), (1, 0.08616476), (2, 0.5079788), (3, 0.21805532), (4, 0.13027166)]
Document 79 Topics: [(0, 0.086966276), (1, 0.08647607), (2, 0.53474104), (3, 0.099869914), (4, 0.1919467)]
Document 80 Topics: [(0, 0.042828005), (1, 0.04224943), (2, 0.70103776), (3, 0.052549917), (4, 0.16133486)]
Document 81 Topics: [(0, 0.042474937), (1, 0.042063404), (2, 0.7639884), (3, 0.052229106), (4, 0.09924419)]
Document 82 Topics: [(0, 0.09033547), (1, 0.045517944), (2, 0.70295537), (3, 0.056062784), (4, 0.10512844)]
Document 83 Topics: [(0, 0.1346187), (1, 0.040402833), (2, 0.6404776), (3, 0.08927502), (4, 0.09522586)]
Document 84 Topics: [(0, 0.07118368), (1, 0.04767378), (2, 0.6672891), (3, 0.05907967), (4, 0.15477376)]
Document 85 Topics: [(0, 0.12939589), (1, 0.05662304), (2, 0.5819482), (3, 0.07061597), (4, 0.16141693)]
Document 86 Topics: [(0, 0.10931939), (1, 0.04444442), (2, 0.5584424), (3, 0.14077404), (4, 0.14701977)]
Document 87 Topics: [(0, 0.27741817), (1, 0.04037833), (2, 0.49814636), (3, 0.050667323), (4, 0.13338985)]
Document 88 Topics: [(0, 0.048803784), (1, 0.04814381), (2, 0.63621837), (3, 0.1063244), (4, 0.16050968)]
Document 89 Topics: [(0, 0.03964898), (1, 0.05872003), (2, 0.51168793), (3, 0.061235625), (4, 0.3287075)]
Document 90 Topics: [(0, 0.053151134), (1, 0.052002963), (2, 0.66050214), (3, 0.065067485), (4, 0.16927627)]
Document 91 Topics: [(0, 0.05994541), (1, 0.059133835), (2, 0.60997206), (3, 0.1306165), (4, 0.14033219)]
Document 92 Topics: [(0, 0.20652801), (1, 0.07817627), (2, 0.50274885), (3, 0.065011576), (4, 0.1475353)]
Document 93 Topics: [(0, 0.22194704), (1, 0.068306096), (2, 0.5057329), (3, 0.07968069), (4, 0.12433331)]
Document 94 Topics: [(0, 0.11371761), (1, 0.05747414), (2, 0.62095296), (3, 0.071487546), (4, 0.13636778)]
Document 95 Topics: [(0, 0.06250491), (1, 0.061755784), (2, 0.6250266), (3, 0.07647913), (4, 0.17423356)]
Document 96 Topics: [(0, 0.06250553), (1, 0.06175727), (2, 0.6250252), (3, 0.07647909), (4, 0.17423287)]
Document 97 Topics: [(0, 0.05514321), (1, 0.05454974), (2, 0.696362), (3, 0.067310974), (4, 0.12663405)]
Document 98 Topics: [(0, 0.060723532), (1, 0.04059403), (2, 0.6931517), (3, 0.050491117), (4, 0.1550396)]
Document 99 Topics: [(0, 0.048187014), (1, 0.047591135), (2, 0.68745476), (3, 0.104904525), (4, 0.11186262)]
Document 100 Topics: [(0, 0.044860587), (1, 0.11157017), (2, 0.6485019), (3, 0.05388933), (4, 0.14117806)]
Document 101 Topics: [(0, 0.13492455), (1, 0.05021915), (2, 0.53491825), (3, 0.14860997), (4, 0.13132809)]
Document 102 Topics: [(0, 0.05673946), (1, 0.0559764), (2, 0.6848837), (3, 0.069626726), (4, 0.13277371)]
Document 103 Topics: [(0, 0.075865924), (1, 0.03834618), (2, 0.6916514), (3, 0.06617872), (4, 0.1279578)]
Document 104 Topics: [(0, 0.122863844), (1, 0.05094984), (2, 0.45639956), (3, 0.061525006), (4, 0.30826172)]
Document 105 Topics: [(0, 0.070458114), (1, 0.06996904), (2, 0.6220119), (3, 0.10562553), (4, 0.13193536)]
Document 106 Topics: [(0, 0.05178087), (1, 0.051146604), (2, 0.71357465), (3, 0.06338284), (4, 0.12011505)]
Document 107 Topics: [(0, 0.061164625), (1, 0.097352736), (2, 0.5953321), (3, 0.07695717), (4, 0.16919342)]
Document 108 Topics: [(0, 0.05856553), (1, 0.058491487), (2, 0.59044284), (3, 0.16388747), (4, 0.12861267)]
Document 109 Topics: [(0, 0.042862386), (1, 0.042306367), (2, 0.6022656), (3, 0.07251213), (4, 0.24005353)]
Document 110 Topics: [(0, 0.056697205), (1, 0.055930264), (2, 0.6582365), (3, 0.069566414), (4, 0.1595696)]
Document 111 Topics: [(0, 0.060729135), (1, 0.059981342), (2, 0.63584536), (3, 0.07423068), (4, 0.16921353)]
Document 112 Topics: [(0, 0.045659143), (1, 0.06674858), (2, 0.52959174), (3, 0.22943991), (4, 0.12856066)]
Document 113 Topics: [(0, 0.045621473), (1, 0.04500457), (2, 0.6163653), (3, 0.0559765), (4, 0.23703218)]
Document 114 Topics: [(0, 0.043009836), (1, 0.08590849), (2, 0.5730988), (3, 0.15863268), (4, 0.13935019)]
Document 115 Topics: [(0, 0.06755941), (1, 0.06836825), (2, 0.5524495), (3, 0.08306607), (4, 0.2285568)]
Document 116 Topics: [(0, 0.045645356), (1, 0.08850973), (2, 0.66023445), (3, 0.056041468), (4, 0.14956897)]
Document 117 Topics: [(0, 0.06319102), (1, 0.062642746), (2, 0.5796477), (3, 0.15697196), (4, 0.13754658)]
Document 118 Topics: [(0, 0.08531222), (1, 0.10555872), (2, 0.6115543), (3, 0.05365176), (4, 0.14392298)]
Document 119 Topics: [(0, 0.043281864), (1, 0.04273735), (2, 0.5558098), (3, 0.053008378), (4, 0.30516258)]
Document 120 Topics: [(0, 0.061939437), (1, 0.061367907), (2, 0.54404175), (3, 0.16332819), (4, 0.16932276)]
Document 121 Topics: [(0, 0.056955513), (1, 0.05744095), (2, 0.51731306), (3, 0.18888262), (4, 0.17940788)]
Document 122 Topics: [(0, 0.08360014), (1, 0.042256575), (2, 0.6194944), (3, 0.05255818), (4, 0.20209068)]
Document 123 Topics: [(0, 0.06756813), (1, 0.08862209), (2, 0.57143027), (3, 0.077921), (4, 0.19445853)]
Document 124 Topics: [(0, 0.053837404), (1, 0.054009553), (2, 0.44635642), (3, 0.24276781), (4, 0.20302878)]
Document 125 Topics: [(0, 0.039002065), (1, 0.038438257), (2, 0.43589628), (3, 0.1563093), (4, 0.33035412)]
Document 126 Topics: [(0, 0.047449954), (1, 0.046912573), (2, 0.58099735), (3, 0.14845283), (4, 0.17618722)]
Document 127 Topics: [(0, 0.11175114), (1, 0.055025093), (2, 0.60021114), (3, 0.06856291), (4, 0.1644497)]
Document 128 Topics: [(0, 0.057830237), (1, 0.08507944), (2, 0.5443154), (3, 0.1257729), (4, 0.18700205)]
Document 129 Topics: [(0, 0.04851444), (1, 0.049910925), (2, 0.47213516), (3, 0.24065484), (4, 0.18878461)]
Document 130 Topics: [(0, 0.051734313), (1, 0.10056572), (2, 0.6399473), (3, 0.063331775), (4, 0.1444209)]
Document 131 Topics: [(0, 0.058910225), (1, 0.05816907), (2, 0.6121969), (3, 0.09909761), (4, 0.17162621)]
Document 132 Topics: [(0, 0.09274058), (1, 0.06461432), (2, 0.574389), (3, 0.08012107), (4, 0.18813507)]
Document 133 Topics: [(0, 0.067131355), (1, 0.17789157), (2, 0.5976968), (3, 0.055018604), (4, 0.10226165)]
Document 134 Topics: [(0, 0.14665203), (1, 0.08866793), (2, 0.5214104), (3, 0.102930166), (4, 0.1403394)]
Document 135 Topics: [(0, 0.0580528), (1, 0.0789182), (2, 0.5134122), (3, 0.20894457), (4, 0.1406722)]
Document 136 Topics: [(0, 0.064997435), (1, 0.043437477), (2, 0.6946756), (3, 0.053769406), (4, 0.14312)]
Document 137 Topics: [(0, 0.06291709), (1, 0.062183462), (2, 0.65248567), (3, 0.076945506), (4, 0.14546822)]
Document 138 Topics: [(0, 0.08488336), (1, 0.08485893), (2, 0.4839245), (3, 0.21497536), (4, 0.13135782)]
Document 139 Topics: [(0, 0.06763785), (1, 0.066723086), (2, 0.5921351), (3, 0.11518902), (4, 0.15831496)]
Document 140 Topics: [(0, 0.05889422), (1, 0.058079224), (2, 0.63652056), (3, 0.07393635), (4, 0.17256965)]
Document 141 Topics: [(0, 0.060656488), (1, 0.089334846), (2, 0.5580203), (3, 0.07267099), (4, 0.21931744)]
Document 142 Topics: [(0, 0.049010772), (1, 0.07034961), (2, 0.47422487), (3, 0.30417988), (4, 0.10223491)]
Document 143 Topics: [(0, 0.049255725), (1, 0.13962492), (2, 0.4662976), (3, 0.074243486), (4, 0.27057824)]
Document 144 Topics: [(0, 0.05752948), (1, 0.05685531), (2, 0.6542109), (3, 0.0980195), (4, 0.13338476)]
Document 145 Topics: [(0, 0.058648072), (1, 0.058093328), (2, 0.51605284), (3, 0.12319494), (4, 0.24401082)]
Document 146 Topics: [(0, 0.11578118), (1, 0.09244821), (2, 0.50834155), (3, 0.05851944), (4, 0.22490963)]
Document 147 Topics: [(0, 0.14182658), (1, 0.061409093), (2, 0.4673913), (3, 0.13140339), (4, 0.19796962)]
Document 148 Topics: [(0, 0.038517263), (1, 0.08512294), (2, 0.5733895), (3, 0.06753071), (4, 0.2354396)]
Document 149 Topics: [(0, 0.092835195), (1, 0.06965208), (2, 0.5127039), (3, 0.16933846), (4, 0.15547045)]
Document 150 Topics: [(0, 0.04943464), (1, 0.04734823), (2, 0.66637534), (3, 0.12696679), (4, 0.109874964)]
Document 151 Topics: [(0, 0.041012824), (1, 0.040523373), (2, 0.44583106), (3, 0.06963114), (4, 0.4030016)]
Document 152 Topics: [(0, 0.06697015), (1, 0.0642696), (2, 0.53859746), (3, 0.1433438), (4, 0.18681896)]
Document 153 Topics: [(0, 0.045828283), (1, 0.04536155), (2, 0.5755423), (3, 0.14335646), (4, 0.18991147)]
Document 154 Topics: [(0, 0.046464145), (1, 0.07595773), (2, 0.5627652), (3, 0.1832422), (4, 0.13157077)]
Document 155 Topics: [(0, 0.12944087), (1, 0.04386939), (2, 0.5649518), (3, 0.1176742), (4, 0.14406374)]
Document 156 Topics: [(0, 0.067568205), (1, 0.08862204), (2, 0.5714302), (3, 0.07792106), (4, 0.19445845)]
Document 157 Topics: [(0, 0.04772149), (1, 0.047078717), (2, 0.68980074), (3, 0.081009775), (4, 0.13438931)]
Document 158 Topics: [(0, 0.058260165), (1, 0.085203715), (2, 0.6209741), (3, 0.07148547), (4, 0.16407654)]
Document 159 Topics: [(0, 0.064401), (1, 0.06362973), (2, 0.64406526), (3, 0.07879092), (4, 0.14911307)]
Document 160 Topics: [(0, 0.06335399), (1, 0.06291825), (2, 0.59198993), (3, 0.10711111), (4, 0.17462672)]
Document 161 Topics: [(0, 0.043566175), (1, 0.046591286), (2, 0.5254655), (3, 0.09763516), (4, 0.28674185)]
Document 162 Topics: [(0, 0.16140933), (1, 0.041326005), (2, 0.6343183), (3, 0.06642625), (4, 0.09652014)]
Document 163 Topics: [(0, 0.085065246), (1, 0.087802015), (2, 0.49247837), (3, 0.07393876), (4, 0.26071557)]
Document 164 Topics: [(0, 0.10216141), (1, 0.051447958), (2, 0.5461769), (3, 0.063077636), (4, 0.2371361)]
Document 165 Topics: [(0, 0.06358175), (1, 0.06274789), (2, 0.6468622), (3, 0.07801356), (4, 0.1487946)]
Document 166 Topics: [(0, 0.06703512), (1, 0.04483278), (2, 0.49799982), (3, 0.16315968), (4, 0.22697258)]
Document 167 Topics: [(0, 0.054525238), (1, 0.05396806), (2, 0.67318356), (3, 0.06647695), (4, 0.15184617)]
Document 168 Topics: [(0, 0.066420764), (1, 0.065626085), (2, 0.601679), (3, 0.08125457), (4, 0.18501958)]
Document 169 Topics: [(0, 0.08564958), (1, 0.057526253), (2, 0.5366692), (3, 0.069100834), (4, 0.2510541)]
Document 170 Topics: [(0, 0.1438032), (1, 0.048650224), (2, 0.6120167), (3, 0.083326235), (4, 0.112203605)]
Document 171 Topics: [(0, 0.12416564), (1, 0.05049465), (2, 0.6183804), (3, 0.06280377), (4, 0.14415555)]
Document 172 Topics: [(0, 0.048198417), (1, 0.04754647), (2, 0.526467), (3, 0.2696732), (4, 0.1081149)]
Document 173 Topics: [(0, 0.069903076), (1, 0.10208323), (2, 0.5786381), (3, 0.08576911), (4, 0.16360651)]
Document 174 Topics: [(0, 0.091632016), (1, 0.09261926), (2, 0.5276265), (3, 0.15928514), (4, 0.12883711)]
Document 175 Topics: [(0, 0.053632967), (1, 0.053046446), (2, 0.6538718), (3, 0.09104807), (4, 0.14840071)]
Document 176 Topics: [(0, 0.062977284), (1, 0.18999754), (2, 0.5264496), (3, 0.076958105), (4, 0.14361742)]
Document 177 Topics: [(0, 0.07472541), (1, 0.14757024), (2, 0.5112177), (3, 0.1325903), (4, 0.13389637)]
Document 178 Topics: [(0, 0.17282988), (1, 0.074829005), (2, 0.4966886), (3, 0.06279983), (4, 0.19285266)]
Document 179 Topics: [(0, 0.07197874), (1, 0.048067536), (2, 0.55010456), (3, 0.22067446), (4, 0.109174676)]
Document 180 Topics: [(0, 0.078195505), (1, 0.07085929), (2, 0.6016725), (3, 0.0872245), (4, 0.16204828)]
Document 181 Topics: [(0, 0.040749885), (1, 0.040239528), (2, 0.69734585), (3, 0.049904376), (4, 0.17176038)]
Document 182 Topics: [(0, 0.07743312), (1, 0.051762454), (2, 0.6586516), (3, 0.06437916), (4, 0.14777368)]
Document 183 Topics: [(0, 0.07946637), (1, 0.07505041), (2, 0.602408), (3, 0.088221736), (4, 0.15485343)]
Document 184 Topics: [(0, 0.09967226), (1, 0.066752814), (2, 0.59218156), (3, 0.08302573), (4, 0.15836763)]
Document 185 Topics: [(0, 0.054102495), (1, 0.053257044), (2, 0.67447793), (3, 0.09194529), (4, 0.1262172)]
Document 186 Topics: [(0, 0.045437317), (1, 0.043990623), (2, 0.6455879), (3, 0.12045536), (4, 0.14452882)]
Document 187 Topics: [(0, 0.06434088), (1, 0.09441705), (2, 0.6135136), (3, 0.07872096), (4, 0.14900756)]

In [ ]:
from gensim.models.coherencemodel import CoherenceModel

# Compute c_v coherence score
coherence_model_lda = CoherenceModel(model=lda_model, texts=tokenized_text, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()

print(f"C_v coherence score: {coherence_lda:.4f}")  # 5 topics =0.3110, 8 topics = 0.3048, 10 topics = 0.2684

C_v coherence score: 0.3110

In [30]:
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis

# Prepare the visualisation
lda_vis = gensimvis.prepare(lda_model, corpus, id2word)
pyLDAvis.show(lda_vis, local=False, open_browser=True)

/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/opt/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=35937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]

127.0.0.1 - - [26/Aug/2025 04:27:34] "GET / HTTP/1.1" 200 -

stopping Server...